// Generated by gencpp from file rosjava_custom_srv/CustomService.msg
// DO NOT EDIT!


#ifndef ROSJAVA_CUSTOM_SRV_MESSAGE_CUSTOMSERVICE_H
#define ROSJAVA_CUSTOM_SRV_MESSAGE_CUSTOMSERVICE_H

#include <ros/service_traits.h>


#include <rosjava_custom_srv/CustomServiceRequest.h>
#include <rosjava_custom_srv/CustomServiceResponse.h>


namespace rosjava_custom_srv
{

struct CustomService
{

typedef CustomServiceRequest Request;
typedef CustomServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomService
} // namespace rosjava_custom_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosjava_custom_srv::CustomService > {
  static const char* value()
  {
    return "43c49944a382f09016b2f4ab1dcb43e7";
  }

  static const char* value(const ::rosjava_custom_srv::CustomService&) { return value(); }
};

template<>
struct DataType< ::rosjava_custom_srv::CustomService > {
  static const char* value()
  {
    return "rosjava_custom_srv/CustomService";
  }

  static const char* value(const ::rosjava_custom_srv::CustomService&) { return value(); }
};


// service_traits::MD5Sum< ::rosjava_custom_srv::CustomServiceRequest> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::CustomService > 
template<>
struct MD5Sum< ::rosjava_custom_srv::CustomServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::CustomService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::CustomServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::CustomServiceRequest> should match 
// service_traits::DataType< ::rosjava_custom_srv::CustomService > 
template<>
struct DataType< ::rosjava_custom_srv::CustomServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::CustomService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::CustomServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosjava_custom_srv::CustomServiceResponse> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::CustomService > 
template<>
struct MD5Sum< ::rosjava_custom_srv::CustomServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::CustomService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::CustomServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::CustomServiceResponse> should match 
// service_traits::DataType< ::rosjava_custom_srv::CustomService > 
template<>
struct DataType< ::rosjava_custom_srv::CustomServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::CustomService >::value();
  }
  static const char* value(const ::rosjava_custom_srv::CustomServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSJAVA_CUSTOM_SRV_MESSAGE_CUSTOMSERVICE_H
